- hosts: {name of server group here}
  tasks:
    - name: Updating repositories 
      apt:
        update_cache: yes
      register: result 

    - name: Upgrading "upgradable" dependencies
      apt:
        name: "*"
        state: latest
      register: result

    - name: Host(s) that were upgraded (if any) 
      shell: grep -E "^$(date +%Y-%m-%d).+ (install|upgrade) " /var/log/dpkg.log |cut -d " " -f 3-5
      register: result

    - name: Dependencies that were upgraded (if any)
      debug: msg="{{ result.stdout_lines }}"

    - name: Cleaning and removing unused dependencies (if any)
      apt:
        autoclean: yes
        autoremove: yes

    - name: Checking if host(s) need rebooting
      ansible.builtin.stat:
        path: /var/run/reboot-required
        get_md5: no
      register: reboot_required_file

    - name: Rebooting host(s) (if required)
      ansible.builtin.reboot:
      when: reboot_required_file.stat.exists == true
 
